dataset:
  video_info_file: ../data/Tianchi/train_annotations_new.json # data/video_info_19993.json
  feat_dir: /data/byh/EventDetection/train/i3d_400/ # data/tsn_anet200/all_csv_mean_100/
  #  video_info_file: data/video_info_19993.json
  #  feat_dir: /data/byh/ActivityNet v1.3/DBG/all_csv_mean_100/
  video_filter: true
  data_aug: true
  tscale: 100
  feature_dim: 1024

saver:
  root_dir: output
  checkpoint_dir: model
  result_dir: result

training:
  learning_rate: [1e-3, 1e-4]
  lr_epochs: [8, 4]
  batch_size: 1

testing:
  mode: validation
  # mode: testing
  batch_size: 1
