dataset:
  dataset_name: activitynet #  activitynet  thumos   tianchi

  tianchi:
    num_classes: 53
    feat_dir: /data/byh/EventDetection/train/i3d_400/
    video_info_file: ../data/Tianchi/train_annotations_new.json
    test_info_file: ../data/Tianchi/val_video_ids.txt
    index_file: ../data/Tianchi/category.json
    test_dir: /data/byh/EventDetection/test/i3d_400/
    video_filter: true
    data_aug: true
    tscale: 100
    feature_dim: 1024


  activitynet:
    num_classes: 200
    feat_dir: /data/byh/ActivityNet v1.3/DBG/all_csv_mean_100/
    video_info_file: ../data/ActivityNet/video_info_19993.json
    test_info_file: ../data/ActivityNet/activity_net_1_3_new.json
    index_file: ../data/ActivityNet/category.json
    test_dir: /data/byh/ActivityNet v1.3/DBG/all_csv_mean_100/
    video_filter: true
    data_aug: true
    tscale: 100
    feature_dim: 400


  thumos:
    feat_dir: /data/byh/THUMOS/xxx
    video_info_file: ../data/THUMOS/xxx
    test_info_file: ../data/THUMOS/xxx
    video_filter: true
    data_aug: true
    tscale: 100
    feature_dim: 400

saver:
  exp_dir: ../exp # 已被log_dir 替代
  results_dir: ../results/
  log_dir: ../logs

training:
  gpu_id: 0
  resume: False  # if load pre-trained model
  learning_rate: 0.0001
  epoch_num: 200
  batch_size: 3

model:
  model_name: DETR  # DBG or DETR

  transformer:
    enc_layers: 16 # Number of encoding layers in the transformer
    dec_layers: 6 # Number of decoding layers in the transformer
    dim_feedforward: 2048 # Intermediate size of the feedforward layers in the transformer blocks
    hidden_dim: 256 # Size of the embeddings (dimension of the transformer)
    dropout: 0.1 # Dropout applied in the transformer
    nheads: 8 # Number of attention heads inside the transformer's attentions
    num_queries: 100 # Number of query slots
    pre_norm: True

  matcher:
    set_cost_classes: 1 # Class coefficient in the matching cost
    set_cost_segments: 5 # L1 box coefficient in the matching cost
    set_cost_diou: 2 # giou box coefficient in the matching cost


testing:
  mode: validation # validation or testing
  test_batch_size: 12
  pth_name: 0712-1737-activitynet # model weights
